
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 16 01:43:21 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 48;
  public static final int CONST = 15;
  public static final int CHAR = 3;
  public static final int GE = 34;
  public static final int LPAREN = 46;
  public static final int SEMI = 42;
  public static final int CONTINUE = 21;
  public static final int MINUS = 27;
  public static final int RPAREN = 47;
  public static final int AND = 37;
  public static final int LT = 35;
  public static final int RECORD = 25;
  public static final int OR = 38;
  public static final int COMMA = 44;
  public static final int BOOL = 4;
  public static final int CLASS = 11;
  public static final int INC = 40;
  public static final int DIV = 29;
  public static final int PLUS = 26;
  public static final int IF = 13;
  public static final int THIS = 22;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 49;
  public static final int EQUAL = 39;
  public static final int SUPER = 23;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 2;
  public static final int MOD = 30;
  public static final int BREAK = 7;
  public static final int IDENT = 5;
  public static final int VOID = 10;
  public static final int EQ = 31;
  public static final int COLON = 43;
  public static final int LBRACE = 50;
  public static final int ELSE = 14;
  public static final int POINT = 45;
  public static final int ENUM = 12;
  public static final int READ = 19;
  public static final int GOTO = 24;
  public static final int WHILE = 17;
  public static final int RBRACE = 51;
  public static final int EXTENDS = 20;
  public static final int PROG = 6;
  public static final int NE = 32;
  public static final int DEC = 41;
  public static final int GT = 33;
  public static final int PRINT = 8;
  public static final int DO = 16;
}

